package com.gitutility.config;

import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class DatabaseSchemaMigratorTest {

    @Test
    void widenH2EnumToVarcharAllowsCancelledStatus() throws Exception {
        try (Connection conn = DriverManager.getConnection("jdbc:h2:mem:enum-widen;DB_CLOSE_DELAY=-1", "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE SYNC_JOBS (
                        ID IDENTITY PRIMARY KEY,
                        STATUS ENUM('DEAD_LETTERED', 'FAILED', 'IN_PROGRESS', 'QUEUED', 'SKIPPED', 'SUCCESS') NOT NULL
                    )
                    """);
            stmt.execute("INSERT INTO SYNC_JOBS(STATUS) VALUES('QUEUED')");

            DatabaseSchemaMigrator.widenH2EnumToVarchar(stmt, "SYNC_JOBS", "STATUS");

            int updated = stmt.executeUpdate("UPDATE SYNC_JOBS SET STATUS='CANCELLED' WHERE ID=1");
            assertEquals(1, updated);
            try (ResultSet rs = stmt.executeQuery("SELECT STATUS FROM SYNC_JOBS WHERE ID=1")) {
                assertTrue(rs.next());
                assertEquals("CANCELLED", rs.getString(1));
            }
        }
    }

    @Test
    void widenCommitMessageAllowsLongSquashMergeBody() throws Exception {
        try (Connection conn = DriverManager.getConnection("jdbc:h2:mem:commit-msg-widen;DB_CLOSE_DELAY=-1", "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE SYNC_JOBS (
                        ID IDENTITY PRIMARY KEY,
                        COMMIT_MESSAGE VARCHAR(1000)
                    )
                    """);
            String longMsg = "feat(agent): make generate_video asynchronous with a placeholder ref (#1267)\n"
                    + "x".repeat(5200);

            try (PreparedStatement ps = conn.prepareStatement("INSERT INTO SYNC_JOBS(COMMIT_MESSAGE) VALUES(?)")) {
                ps.setString(1, longMsg);
                SQLException rejected = assertThrows(SQLException.class, ps::executeUpdate);
                assertTrue(rejected.getMessage().contains("too long") || rejected.getMessage().contains("22001"),
                        rejected.getMessage());
            }

            DatabaseSchemaMigrator.widenVarcharToClob(stmt, "SYNC_JOBS", "COMMIT_MESSAGE");

            try (PreparedStatement ps = conn.prepareStatement("INSERT INTO SYNC_JOBS(COMMIT_MESSAGE) VALUES(?)")) {
                ps.setString(1, longMsg);
                assertEquals(1, ps.executeUpdate());
            }
            try (ResultSet rs = stmt.executeQuery("SELECT LENGTH(COMMIT_MESSAGE) FROM SYNC_JOBS")) {
                assertTrue(rs.next());
                assertEquals(longMsg.length(), rs.getInt(1));
            }
        }
    }

    @Test
    void addsForkPrHeadColumnAndRefOriginsTable() throws Exception {
        try (Connection conn = DriverManager.getConnection("jdbc:h2:mem:pr-origin;DB_CLOSE_DELAY=-1", "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE pr_mappings (id IDENTITY PRIMARY KEY, mapping_id BIGINT)");
            stmt.execute("ALTER TABLE pr_mappings ADD COLUMN IF NOT EXISTS fork_pr_head BOOLEAN DEFAULT FALSE");
            stmt.execute("ALTER TABLE pr_mappings ADD COLUMN IF NOT EXISTS origin_side VARCHAR(8)");
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS ref_origins (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        mapping_id BIGINT NOT NULL,
                        ref_name VARCHAR(512) NOT NULL,
                        origin_side VARCHAR(8) NOT NULL,
                        created_at TIMESTAMP,
                        CONSTRAINT uk_ref_origins_mapping_ref UNIQUE (mapping_id, ref_name)
                    )
                    """);
            stmt.execute("INSERT INTO pr_mappings(mapping_id, fork_pr_head, origin_side) VALUES(4, TRUE, 'A')");
            try (ResultSet rs = stmt.executeQuery("SELECT FORK_PR_HEAD, ORIGIN_SIDE FROM pr_mappings WHERE id=1")) {
                assertTrue(rs.next());
                assertTrue(rs.getBoolean(1));
                assertEquals("A", rs.getString(2));
            }
            stmt.execute("INSERT INTO ref_origins(mapping_id, ref_name, origin_side) VALUES(4, 'refs/heads/feat', 'B')");
            try (ResultSet rs = stmt.executeQuery("SELECT origin_side FROM ref_origins WHERE ref_name='refs/heads/feat'")) {
                assertTrue(rs.next());
                assertEquals("B", rs.getString(1));
            }
        }
    }

    @Test
    void addsConflictPolicyCasColumnsAndSyncConflictsTable() throws Exception {
        try (Connection conn = DriverManager.getConnection("jdbc:h2:mem:conflicts;DB_CLOSE_DELAY=-1", "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE TABLE repo_mappings (id IDENTITY PRIMARY KEY)");
            stmt.execute("CREATE TABLE pr_mappings (id IDENTITY PRIMARY KEY, mapping_id BIGINT)");
            stmt.execute("ALTER TABLE repo_mappings ADD COLUMN IF NOT EXISTS trunk_conflict_policy VARCHAR(20) DEFAULT 'ISOLATE'");
            stmt.execute("ALTER TABLE pr_mappings ADD COLUMN IF NOT EXISTS last_pushed_title VARCHAR(1000)");
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS sync_conflicts (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        mapping_id BIGINT NOT NULL,
                        kind VARCHAR(20) NOT NULL,
                        status VARCHAR(20) NOT NULL
                    )
                    """);
            stmt.execute("INSERT INTO repo_mappings(trunk_conflict_policy) VALUES('ORIGIN_WINS')");
            stmt.execute("INSERT INTO sync_conflicts(mapping_id, kind, status) VALUES(1, 'GIT_REF', 'OPEN')");
            try (ResultSet rs = stmt.executeQuery("SELECT trunk_conflict_policy FROM repo_mappings")) {
                assertTrue(rs.next());
                assertEquals("ORIGIN_WINS", rs.getString(1));
            }
            try (ResultSet rs = stmt.executeQuery("SELECT kind FROM sync_conflicts")) {
                assertTrue(rs.next());
                assertEquals("GIT_REF", rs.getString(1));
            }
        }
    }
}
